CREATE TABLE d_episodes (
    id SERIAL PRIMARY KEY,
    season_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    thumbnail_url TEXT,
    original_video_url TEXT,
    stream_video_url TEXT,
    available_status VARCHAR(50),
    episode_order INT,
    rate FLOAT,
    total_rate INT,
    total_viewer INT,
    total_upvote INT,
    total_downvote INT,
    duration INT,
    release_date DATE,
    created_by VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);